services:
  proxy:
    image: nginx:1.24.0-alpine
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./services/proxy/conf.d:/etc/nginx/conf.d
      - ${PROXY_CMS_CERT_PATH}:/var/certs/cms-cert.pem
      - ${PROXY_CMS_CERT_KEY_PATH}:/var/certs/cms-cert-key.pem
      - ${PROXY_WWW_CERT_PATH}:/var/certs/www-cert.pem
      - ${PROXY_WWW_CERT_KEY_PATH}:/var/certs/www-cert-key.pem
    ports:
      - ${HTTP_PORT:-8080}:443

  db:
    image: mysql:8.0.30-oracle
    command:
      - --authentication_policy=mysql_native_password
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_USER: ${DB_USER:-dev}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-dev}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306

  redis:
    image: redis:6.2.14-alpine
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT:-6379}:6379

  cms:
    depends_on:
      - db
    build:
      context: ./services/cms
      dockerfile: dev.Dockerfile
      args:
        PUBLIC_URL: https://cms.turugi-mahiru.fans.127.0.0.1.nip.io:${HTTP_PORT:-8080}/
    volumes:
      - ./services/cms:/app

  # ytlive
  ytlive-sync:
    profiles:
      - ytlive
    depends_on:
      - cms
    build:
      context: ./services/ytlive-sync
      dockerfile: Dockerfile
    environment:
      REDIS_URI: ${REDIS_URI:-redis://redis/1}
      YT_CHANNEL_ID: ${YTLIVE_SYNC_YT_CHANNEL_ID:-UCSzT-rU62SSiham-g1Dj9yw}

  # ranking
  ranking-aggregate:
    profiles:
      - ranking
    depends_on:
      - cms
    build:
      context: ./services/ranking-aggregate
      dockerfile: Dockerfile

  # www
  www:
    profiles:
      - www
    depends_on:
      - cms
    build:
      context: ./services/www
      dockerfile: dev.Dockerfile
      args:
        CMS_PUBLIC_URL: https://cms.turugi-mahiru.fans.127.0.0.1.nip.io:${HTTP_PORT:-8080}/
        PUBLIC_URL: https://www.turugi-mahiru.fans.127.0.0.1.nip.io:${HTTP_PORT:-8080}/
    environment:
      REDIS_URI: ${REDIS_URI:-redis://redis/1}
    volumes:
      - ./services/www:/app
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/secrets/firebase-admin.json

volumes:
  db_data:
  redis_data:
