version: "3"

services:
  strapi:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - strapi_uploads:/opt/app/public/uploads
    restart: always

volumes:
  strapi_uploads:

